# -*- coding: utf-8 -*-
{
    'name': "POS Features Collection| POS Features In One| POS Direct Login| POS Quick Pay| POS SalesPerson| POS Order Note| POS Session Report| POS Screen Lock| POS Clear Cart| POS Disable Buttons| POS Default Invoice| POS Default Customer| POS Sync Order| POS Customer Required| POS Product Limit| POS Receipt Logo| POS Hide Numpad| POS Hide Product Info| Pos Bag Charge| POS Item Count| POS Barcode| POS Internal Refrence| POS Onhand Restrict Zero Quantity| POS Product Image",

    'summary': """ pos features in one pos direct login pos quick pay pos sales person pos order note pos session report 
    pos screen lock pos clear cart pos disable control buttons pos default invoice pos default customer pos mandatory 
    customer pos order sync pos product limit pos receipt pos receipt logo pos show product barcode 
    pos show product internal reference pos item count pos receipt item count pos bag charge 
    pos hide product info pos hide numpad pos restrict zero onhand quantity""",

    'description': """this is retail features for any kind of retail businesses""",
    'author': "Khaled Hassan",
    'website': "https://apps.odoo.com/apps/modules/browse?search=Khaled+hassan",
    'category': 'Point of Sale',
    'version': '16.0.1.0',
    'depends': ['base', 'point_of_sale', 'pos_hr', 'hr','product_app_knk'],
    'data': [
        'security/ir.model.access.csv',
        'views/pos_config_views.xml',
        'views/res_users.xml',
        'views/pos_session_report.xml',
        'views/pos_order.xml',
        'wizard/close_session_report_view.xml',
        #'views/templates.xml',
    ],
    'assets': {
        'point_of_sale.assets': [
            #'pos_features_in_one/static/src/js/PosClearOrderLine.js',
            'pos_features_in_one/static/src/js/ClearAllCart.js',
            'pos_features_in_one/static/src/js/PosCustomerMandatory.js',
            'pos_features_in_one/static/src/js/PosDefaultCustomer.js',
            'pos_features_in_one/static/src/js/PosDefaultInvoice.js',
            'pos_features_in_one/static/src/js/PosDisableButtons.js',
            'pos_features_in_one/static/src/js/PosProductLimit.js',
            'pos_features_in_one/static/src/js/PosReceiptLogo.js',
            'pos_features_in_one/static/src/js/PosScreenLock.js',
            'pos_features_in_one/static/src/js/PosSessionReport.js',
            #'pos_features_in_one/static/src/js/PosSyncOrder.js',
            'pos_features_in_one/static/src/js/PosTotalQuantProduct.js',
            'pos_features_in_one/static/src/js/PosTotalQuantReceipt.js',
            'pos_features_in_one/static/src/js/PosZeroQtyRestrict.js',
            'pos_features_in_one/static/src/js/QuickPay.js',
            'pos_features_in_one/static/src/js/ShowHideNumpad.js',
            'pos_features_in_one/static/src/js/SalesPerson.js',
            'pos_features_in_one/static/src/js/SalesPersonPopup.js',
            'pos_features_in_one/static/src/js/models.js',
            'pos_features_in_one/static/src/js/SalesPersonOrderline.js',
            'pos_features_in_one/static/src/js/PosBagChargeButton.js',
            'pos_features_in_one/static/src/js/PosBagChargePopup.js',
            'pos_features_in_one/static/src/js/PosNoteModel.js',
            'pos_features_in_one/static/src/js/PosNoteButton.js',
            'pos_features_in_one/static/src/js/PosOrderNoteWidget.js',

            'pos_features_in_one/static/src/xml/HideNumpad.xml',
            'pos_features_in_one/static/src/xml/ClearAllCart.xml',
            'pos_features_in_one/static/src/xml/PosClearOrderLine.xml',
            #'pos_features_in_one/static/src/xml/PosInternalRef.xml',
            'pos_features_in_one/static/src/xml/PosItemsCount.xml',
            #'pos_features_in_one/static/src/xml/PosOrderImage.xml',
            'pos_features_in_one/static/src/xml/PosReceiptItemCount.xml',
            'pos_features_in_one/static/src/xml/PosReceiptLogo.xml',
            'pos_features_in_one/static/src/xml/PosSessionReport.xml',
            #'pos_features_in_one/static/src/xml/PosSyncOrder.xml',
            'pos_features_in_one/static/src/xml/ProductInfoButton.xml',
            'pos_features_in_one/static/src/xml/quick_pay.xml',
            'pos_features_in_one/static/src/xml/SalesPerson.xml',
            'pos_features_in_one/static/src/xml/SalesPersonPopup.xml',
            'pos_features_in_one/static/src/xml/PosBagCharge.xml',
            'pos_features_in_one/static/src/xml/PosNoteButton.xml',
            'pos_features_in_one/static/src/xml/PosOrderNoteWidget.xml',
            'pos_features_in_one/static/src/xml/PosNoteReceipt.xml',
            #'pos_features_in_one/static/src/scss/pos.scss',
        ],
    },
    "application": True,
    "license": "OPL-1",
    "auto_install": False,
    "installable": True,
    "price": 80,
    "currency": "EUR",
}
