{
    'name': 'Sale Order PDVSA Flag',
    'version': '16.0.1.0.0',
    'summary': 'Marca automáticamente los pedidos de venta cuyo cliente contenga "PDVSA".',
    'category': 'Sales',
    'author': 'Samir Espina by Contables',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['sale'],
    'data': [
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'security/pdvsa_security.xml',
        'security/ir.model.access.csv',
        'wizard/sale_order_pdvsa_invoice_wizard_views.xml',
        'wizard/sale_order_pdvsa_mass_invoice_wizard_views.xml',
        'wizard/sale_order_pdvsa_mass_invoice_wizard_menu.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
