{
    'name': 'Inventario a la Fecha por Ubicaciones',
    'version': '16.0.1.0.0',
    'category': 'Inventory',
    'summary': 'Inventario a la Fecha: selección de ubicaciones (extensión mínima)',
    'description': """
Extensión del reporte 'Inventario a la Fecha' (Odoo 16) para detallar inventario histórico por ubicación.

Características:
 - Selección de múltiples ubicaciones en el wizard nativo.
 - Opción de agrupación inicial por almacén.
 - Desglose de líneas Producto/Ubicación con cantidad, costo y valor total.
 - Vistas árbol, pivote y búsqueda con filtros y agrupaciones.
""",
    'author': 'AutoGenerated',
    'license': 'LGPL-3',
    'depends': ['stock'],
    'data': [
        'security/ir.model.access.csv',
    'views/inventory_at_date_views.xml',
    'views/product_inventory_breakdown_tree.xml',
    ],
    'installable': True,
    'application': False,
}
